# Generated by Django 2.2.28 on 2024-11-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='day', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du personnage')),
                ('role', models.CharField(choices=[('loup_garou', 'Loup Garou'), ('villageois', 'Villageois'), ('sorciere', 'Sorcière'), ('garde', 'Garde'), ('chasseur', 'Chasseur'), ('voyante', 'Voyante')], max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('alive', 'Vivant'), ('dead', 'Mort')], default='alive', max_length=5, verbose_name='Statut')),
                ('has_used_power', models.BooleanField(default=False, verbose_name='Pouvoir utilisé')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnages', to='jeu.Game')),
            ],
        ),
    ]
