# Generated by Django 2.2.28 on 2024-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='game',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=5),
        ),
    ]
