# Generated by Django 2.2.4 on 2024-11-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0003_auto_20241119_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id_character', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('gentil', 'Gentil'), ('mechant', 'Méchant')], max_length=20)),
                ('etat', models.CharField(choices=[('vivant', 'Vivant'), ('en danger', 'En Danger'), ('mort', 'Mort')], default='vivant', max_length=20)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equip', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('taille_max', models.IntegerField(default=1)),
                ('disponibilite', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], default='libre', max_length=20)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Personnage',
        ),
        migrations.AddField(
            model_name='character',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.Equipement'),
        ),
    ]
