# Generated by Django 2.2.4 on 2024-11-21 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0004_auto_20241121_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id_lieu', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('disponibilite', models.CharField(default='libre', max_length=20)),
                ('taille_max', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id_personnage', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('villageois', 'Villageois'), ('loup_garou', 'Loup-Garou'), ('sorciere', 'Sorcière'), ('garde', 'Garde')], max_length=20)),
                ('etat', models.CharField(choices=[('vivant', 'Vivant'), ('mort', 'Mort'), ('endormi', 'Endormi')], default='vivant', max_length=20)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.Lieu')),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
