# Generated by Django 2.2.4 on 2024-11-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0005_auto_20241121_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnage',
            name='est_protege',
            field=models.BooleanField(default=False),
        ),
    ]
