# Generated by Django 2.2.4 on 2024-11-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0006_personnage_est_protege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('jour', 'Jour'), ('nuit', 'Nuit')], default='jour', max_length=10)),
            ],
        ),
    ]
